import { ArrowRight, Scissors, Sparkles, UsersRound, WandSparkles } from 'lucide-react';
import { Link } from 'wouter';
import { useEffect, useState } from 'react';

const serviceGroups = [
  { id: 'hair', icon: Scissors, label: 'Hair', title: 'Hair that feels like you', copy: 'Thoughtful cuts, styling, colour, and care shaped around your texture, routine, and sense of style.', items: ['Cuts and styling', 'Colour conversations', 'Hair care rituals'] },
  { id: 'beauty', icon: Sparkles, label: 'Beauty & skincare', title: 'A little more glow', copy: 'Beauty and skincare rituals designed to leave you feeling refreshed, looked after, and ready for what is next.', items: ['Facials and skincare', 'Beauty rituals', 'Brows and finishing touches'] },
  { id: 'grooming', icon: UsersRound, label: 'Grooming', title: 'Good grooming, made easy', copy: 'A considered refresh for men and women, with the detail and ease your everyday deserves.', items: ['Grooming refreshes', 'Styling and finishing', 'Occasion-ready details'] },
  { id: 'bridal', icon: WandSparkles, label: 'Bridal', title: 'For the moments that matter', copy: 'A calm, personal approach to bridal beauty, from early planning to the final detail.', items: ['Bridal hair', 'Bridal beauty', 'Event-ready planning'] },
];

export default function Services() {
  const [active, setActive] = useState('hair');
  useEffect(() => { const title = 'Services | Naturals Salon & Spa Hyderabad'; const description = 'Explore hair, beauty, grooming, skincare, and bridal services at Naturals Salon & Spa Hyderabad.'; document.title = title; for (const [key, content] of [['name', description], ['property', description]] as const) { const selector = key === 'name' ? 'meta[name="description"]' : 'meta[property="og:description"]'; const meta = document.querySelector(selector) ?? document.createElement('meta'); meta.setAttribute(key, content); meta.setAttribute('content', content); document.head.appendChild(meta); } }, []);
  return <main>
    <section className="bg-primary py-20 text-primary-foreground md:py-28"><div className="section-shell grid gap-10 md:grid-cols-[1.1fr_.9fr] md:items-end"><div><p className="eyebrow !text-accent">Our services</p><h1 className="font-display mt-5 max-w-2xl text-5xl leading-[1.02] md:text-7xl">Care, tailored to the way <em>you live.</em></h1></div><p className="max-w-sm text-base leading-8 text-primary-foreground/70">No two visits should feel the same. Browse the rituals we offer and tell us what you are looking for.</p></div></section>
    <section className="section-shell py-20 md:py-28"><div className="grid gap-3 md:grid-cols-4">{serviceGroups.map((group) => { const Icon = group.icon; return <button type="button" data-testid={`button-service-tab-${group.id}`} key={group.id} onClick={() => setActive(group.id)} className={`flex items-center gap-3 rounded-xl border p-4 text-left transition-all md:block md:min-h-[122px] md:p-5 ${active === group.id ? 'border-primary bg-primary text-primary-foreground shadow-[var(--shadow-sm)]' : 'border-border bg-card text-primary hover:border-primary/40'}`}><Icon size={20} className={active === group.id ? 'text-accent' : 'text-primary'} /><span className="mt-3 block text-sm font-bold">{group.label}</span></button>; })}</div>
      {serviceGroups.filter((group) => group.id === active).map((group) => { const Icon = group.icon; return <div key={group.id} className="mt-14 grid gap-10 border-t border-border pt-10 md:grid-cols-[.75fr_1.25fr]"><div><div className="grid size-14 place-items-center rounded-full bg-accent/25 text-primary"><Icon size={25} /></div><p className="eyebrow mt-8">{group.label}</p><h2 className="font-display mt-3 text-4xl leading-tight text-primary md:text-6xl">{group.title}</h2></div><div><p className="max-w-xl text-base leading-8 text-muted-foreground">{group.copy}</p><div className="mt-9 grid max-w-xl gap-0 border-t border-border">{group.items.map((item, index) => <div key={item} className="flex items-center justify-between border-b border-border py-5 text-sm font-semibold text-primary"><span><span className="mr-4 text-xs font-normal text-accent">0{index + 1}</span>{item}</span><ArrowRight size={16} className="text-accent" /></div>)}</div><p className="mt-7 text-xs text-muted-foreground">Services are tailored after a personal consultation. Please enquire for details.</p><Link href="/contact" data-testid="link-services-book" className="mt-8 inline-flex items-center gap-3 rounded-full bg-accent px-6 py-4 text-xs font-bold uppercase tracking-widest text-accent-foreground">Enquire about this <ArrowRight size={15} /></Link></div></div>; })}
    </section>
    <section className="bg-secondary/60 py-20"><div className="section-shell flex flex-col justify-between gap-8 md:flex-row md:items-center"><div><p className="eyebrow">Not sure where to start?</p><h2 className="font-display mt-3 text-4xl text-primary">Tell us what you need.</h2></div><Link href="/contact" data-testid="link-services-contact" className="inline-flex items-center gap-3 self-start rounded-full border border-primary px-6 py-4 text-xs font-bold uppercase tracking-widest text-primary transition-colors hover:bg-primary hover:text-primary-foreground">Talk to the team <ArrowRight size={15} /></Link></div></section>
  </main>;
}